import type { Database } from "./types";

export type SeedProperty = Omit<
  Database["public"]["Tables"]["properties"]["Insert"],
  "id" | "created_at" | "updated_at" | "views"
> & { slug: string };

export type SeedAgent = Omit<
  Database["public"]["Tables"]["agents"]["Insert"],
  "id" | "created_at" | "updated_at"
>;

export type SeedTestimonial = Omit<
  Database["public"]["Tables"]["testimonials"]["Insert"],
  "id" | "created_at"
>;

export const SEED_PROPERTIES: SeedProperty[] = [
  {
    title: "Luxury 4-Bedroom Detached Duplex",
    slug: "luxury-4-bedroom-detached-duplex-lekki",
    price: 120_000_000,
    listing_type: "sale",
    property_type: "house",
    beds: 4,
    baths: 5,
    size_sqm: 450,
    address: "Plot 12, Admiralty Way",
    city_area: "Lekki Phase 1",
    city: "Lagos",
    description:
      "Exquisitely designed 4-bedroom detached duplex in the heart of Lekki Phase 1. Features imported Italian tiles, a modern open-plan kitchen, a private cinema room, and a swimming pool. Estate services include 24-hour security and constant power supply.",
    features: [
      "Swimming Pool",
      "Private Cinema",
      "Smart Home System",
      "24/7 Security",
      "Parking for 4 Cars",
      "Staff Quarters",
      "Central Air Conditioning",
      "Imported Italian Tiles",
    ],
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    ],
    is_featured: true,
    status: "available",
    lat: 6.4475,
    lng: 3.4552,
    agent_id: null,
  },
  {
    title: "Modern 3-Bedroom Terrace Apartment",
    slug: "modern-3-bedroom-terrace-victoria-island",
    price: 85_000_000,
    listing_type: "sale",
    property_type: "apartment",
    beds: 3,
    baths: 3,
    size_sqm: 280,
    address: "Adeola Odeku Street",
    city_area: "Victoria Island",
    city: "Lagos",
    description:
      "Stunning 3-bedroom terrace apartment on the prestigious Adeola Odeku Street. Boasts floor-to-ceiling windows, a gourmet kitchen, en-suite bedrooms, and a private terrace. Minutes from top restaurants, banks, and corporate offices.",
    features: [
      "Floor-to-Ceiling Windows",
      "Gourmet Kitchen",
      "En-suite Bathrooms",
      "Private Terrace",
      "Generator House",
      "CCTV Surveillance",
      "Elevator",
      "Serviced Estate",
    ],
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    ],
    is_featured: true,
    status: "available",
    lat: 6.4281,
    lng: 3.4219,
    agent_id: null,
  },
  {
    title: "Elegant 5-Bedroom Mansion",
    slug: "elegant-5-bedroom-mansion-ikoyi",
    price: 350_000_000,
    listing_type: "sale",
    property_type: "house",
    beds: 5,
    baths: 6,
    size_sqm: 800,
    address: "Off Alexander Avenue",
    city_area: "Ikoyi",
    city: "Lagos",
    description:
      "A breathtaking 5-bedroom mansion in the exclusive Ikoyi neighbourhood. This architectural masterpiece features a grand living room, wine cellar, home office, gym, and lush landscaped garden. A true statement of luxury living.",
    features: [
      "Wine Cellar",
      "Home Gym",
      "Grand Living Room",
      "Landscaped Garden",
      "Home Office",
      "Servant Quarter",
      "Intercom System",
      "Water Treatment Plant",
    ],
    images: [
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80",
    ],
    is_featured: true,
    status: "available",
    lat: 6.4490,
    lng: 3.4260,
    agent_id: null,
  },
  {
    title: "2-Bedroom Serviced Apartment (Annual Rent)",
    slug: "2-bedroom-serviced-apartment-chevron",
    price: 15_000_000,
    listing_type: "rent",
    property_type: "apartment",
    beds: 2,
    baths: 2,
    size_sqm: 160,
    address: "Osapa London, off Chevron Estate Road",
    city_area: "Chevron",
    city: "Lagos",
    description:
      "Fully serviced 2-bedroom apartment in a serene part of Chevron Estate. Furnished to international standards, ideal for expatriates and short-let conversions. Includes power, water, and estate security in service charge.",
    features: [
      "Fully Furnished",
      "24/7 Power Supply",
      "Swimming Pool Access",
      "Gated Estate",
      "Parking Space",
      "Laundry Room",
      "CCTV",
    ],
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
      "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
    ],
    is_featured: false,
    status: "available",
    lat: 6.4620,
    lng: 3.4550,
    agent_id: null,
  },
  {
    title: "Spacious 3-Bedroom Flat",
    slug: "spacious-3-bedroom-flat-ikeja",
    price: 5_000_000,
    listing_type: "rent",
    property_type: "apartment",
    beds: 3,
    baths: 2,
    size_sqm: 180,
    address: "Mobolaji Bank Anthony Way",
    city_area: "Ikeja",
    city: "Lagos",
    description:
      "Well-maintained 3-bedroom flat in a quiet, accessible part of Ikeja GRA. Close to the Ikeja City Mall, hospitals, and government offices. Ideal for families seeking a comfortable neighbourhood.",
    features: [
      "En-suite Master Bedroom",
      "Spacious Living Room",
      "Kitchen with Pantry",
      "Car Park (2 Cars)",
      "24-Hour Security",
      "Perimeter Fencing",
    ],
    images: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
      "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800&q=80",
      "https://images.unsplash.com/photo-1560185008-b033106af5c8?w=800&q=80",
    ],
    is_featured: false,
    status: "available",
    lat: 6.6059,
    lng: 3.3496,
    agent_id: null,
  },
  {
    title: "Prime Commercial Office Space",
    slug: "prime-commercial-office-space-victoria-island",
    price: 45_000_000,
    listing_type: "lease",
    property_type: "land",
    beds: 0,
    baths: 4,
    size_sqm: 500,
    address: "Bourdillon Road",
    city_area: "Victoria Island",
    city: "Lagos",
    description:
      "Grade-A commercial office space on Bourdillon Road, Victoria Island. Open-plan layout suitable for corporate headquarters or financial institutions. Close to the Eko Hotel, banks, and embassies.",
    features: [
      "Open-Plan Layout",
      "Central Air Conditioning",
      "Fibre Optic Internet",
      "Elevator (2 Lifts)",
      "Underground Parking",
      "Security Guard",
      "Reception Area",
      "Server Room",
    ],
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80",
      "https://images.unsplash.com/photo-1564069114553-7215e1ff1890?w=800&q=80",
    ],
    is_featured: false,
    status: "available",
    lat: 6.4334,
    lng: 3.4196,
    agent_id: null,
  },
  {
    title: "Charming 4-Bedroom Bungalow",
    slug: "charming-4-bedroom-bungalow-yaba",
    price: 75_000_000,
    listing_type: "sale",
    property_type: "house",
    beds: 4,
    baths: 3,
    size_sqm: 300,
    address: "Herbert Macaulay Way, Yaba",
    city_area: "Yaba",
    city: "Lagos",
    description:
      "A charming 4-bedroom bungalow in the vibrant Yaba neighbourhood. Featuring a spacious compound, modern kitchen, and staff quarter. Ideal for families who enjoy being in the heart of Lagos commercial activity.",
    features: [
      "Staff Quarters",
      "Spacious Compound",
      "Modern Kitchen",
      "Generator House",
      "Perimeter Fence",
      "Water Well",
    ],
    images: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80",
    ],
    is_featured: false,
    status: "available",
    lat: 6.5158,
    lng: 3.3896,
    agent_id: null,
  },
  {
    title: "Luxury 2-Bedroom Short-Let Apartment",
    slug: "luxury-2-bedroom-short-let-gbagada",
    price: 500_000,
    listing_type: "rent",
    property_type: "apartment",
    beds: 2,
    baths: 2,
    size_sqm: 120,
    address: "Gbagada Phase 2, off Thomas Salako Street",
    city_area: "Gbagada",
    city: "Lagos",
    description:
      "Beautifully furnished 2-bedroom short-let apartment in Gbagada. Perfect for business travellers, featuring high-speed Wi-Fi, smart TV, fully equipped kitchen, and convenient access to the Third Mainland Bridge.",
    features: [
      "Fully Furnished",
      "High-Speed Wi-Fi",
      "Smart TV",
      "Air Conditioning",
      "Kitchen Appliances",
      "Secure Parking",
      "24-Hour Power",
    ],
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    ],
    is_featured: false,
    status: "available",
    lat: 6.5260,
    lng: 3.3900,
    agent_id: null,
  },
];

export const SEED_AGENTS: SeedAgent[] = [
  {
    name: "Adaeze Obi",
    role: "Senior Property Consultant",
    phone: "+234 801 234 5678",
    whatsapp: "+234 801 234 5678",
    email: "adaeze.obi@ginterior.ng",
    photo_url: "/brand/logo.jpeg",
    bio: "Adaeze brings over 8 years of luxury real estate experience in Lagos Island and Mainland. She specialises in high-value residential sales and has an unmatched network of buyers and sellers.",
    active: true,
  },
  {
    name: "Chidi Eze",
    role: "Leasing & Commercial Specialist",
    phone: "+234 802 345 6789",
    whatsapp: "+234 802 345 6789",
    email: "chidi.eze@ginterior.ng",
    photo_url: "/brand/logo.jpeg",
    bio: "Chidi is our go-to expert for commercial leases and long-term lettings. His deep knowledge of Victoria Island and Lekki Grade-A office markets makes him invaluable to corporate clients.",
    active: true,
  },
  {
    name: "Tunde Bakare",
    role: "Interior Design & Property Advisory",
    phone: "+234 803 456 7890",
    whatsapp: "+234 803 456 7890",
    email: "tunde.bakare@ginterior.ng",
    photo_url: "/brand/logo.jpeg",
    bio: "Tunde bridges the gap between property and design. With a background in architecture and interior styling, he helps clients find homes and transform them into dream spaces.",
    active: true,
  },
];

export const SEED_TESTIMONIALS: SeedTestimonial[] = [
  {
    client_name: "Ngozi A.",
    text: "G Interior helped us find our dream home in Lekki within two weeks. Their attention to detail and knowledge of the market is unmatched. I would highly recommend them to anyone looking for property in Lagos.",
    rating: 5,
    approved: true,
  },
  {
    client_name: "Emeka O.",
    text: "As a first-time buyer, I was nervous about the process. The team walked me through every step, from inspections to closing. Professional, transparent, and truly invested in their clients.",
    rating: 5,
    approved: true,
  },
  {
    client_name: "Sarah J.",
    text: "We needed an office space urgently for our expanding team. Chidi at G Interior found us the perfect spot on Victoria Island within our budget. Efficient and highly professional service.",
    rating: 5,
    approved: true,
  },
  {
    client_name: "Babatunde K.",
    text: "The interior design consultation was a game changer. Tunde completely reimagined our living space and it now looks like something out of a magazine. We could not be happier with the result.",
    rating: 5,
    approved: true,
  },
];
